module.exports = crypto => {
    const cryptocurrencies = {
        "btc": "bitcoin",
        "eth": "ethereum",
        "usdt": "tether",
        "bnb": "binancecoin",
        "xrp": "ripple",
        "ada": "cardano",
        "doge": "dogecoin",
        "sol": "solana",
        "dot": "polkadot",
        "shib": "shibainu",
        "trx": "tron",
        "ltc": "litecoin",
        "avax": "avalanche",
        "link": "chainlink",
        "atom": "cosmos",
        "uni": "uniswap",
        "xlm": "stellar",
        "xmr": "monero",
        "vet": "vechain",
        "aave": "aave",
        "fil": "filecoin",
        "eos": "eos",
        "algo": "algorand",
        "theta": "theta",
        "xtz": "tezos",
        "egld": "elrond",
        "mkr": "maker",
        "axs": "axieinfinity",
        "ftm": "fantom",
        "one": "harmony",
        "zec": "zcash",
        "dash": "dash",
        "neo": "neo",
        "kcs": "kucoinToken",
        "miota": "iota",
        "mana": "decentraland",
        "chz": "chiliz",
        "enj": "enjincoin",
        "celo": "celo",
        "hnt": "helium",
        "cake": "pancakeswap",
        "sushi": "sushiswap",
        "flow": "flow",
        "crv": "curvedao",
        "yfi": "yearnfinance",
        "snx": "synthetix",
        "comp": "compound",
        "lunc": "terraclassic",
        "bch": "bitcoincash"
    };

    const cryptoName = cryptocurrencies[crypto.toLowerCase()];
    return cryptoName;
};