module.exports = fiat => {
    const fiatCurrencies = {
        "dollar": "usd",
        "euro": "eur",
        "pound": "gbp",
        "yen": "jpy",
        "franc": "chf",
        "rupee": "inr",
        "yuan": "cny",
        "won": "krw",
        "lira": "try",
        "ruble": "rub",
        "dinar": "iqd",
        "rial": "irr",
        "peso": "mxn",
        "australian dollar": "aud",
        "canadian dollar": "cad",
        "swedish krona": "sek",
        "norwegian krone": "nok",
        "danish krone": "dkk",
        "new zealand dollar": "nzd",
        "singapore dollar": "sgd",
        "hong kong dollar": "hkd",
        "thai baht": "thb",
        "south african rand": "zar",
        "brazilian real": "brl",
        "philippine peso": "php",
        "chilean peso": "clp",
        "colombian peso": "cop",
        "egyptian pound": "egp",
        "saudi riyal": "sar",
        "emirati dirham": "aed",
        "kuwaiti dinar": "kwd",
        "qatari riyal": "qar",
        "bahraini dinar": "bhd",
        "omani rial": "omr",
        "jordanian dinar": "jod",
        "pakistani rupee": "pkr",
        "bangladeshi taka": "bdt",
        "indonesian rupiah": "idr",
        "malaysian ringgit": "myr",
        "vietnamese dong": "vnd",
        "taiwan dollar": "twd",
        "israeli shekel": "ils",
        "hungarian forint": "huf",
        "polish zloty": "pln",
        "czech koruna": "czk",
        "romanian leu": "ron",
        "bulgarian lev": "bgn",
        "icelandic krona": "isk",
        "croatian kuna": "hrk",
        "turkmen manat": "tmt",
        "armenian dram": "amd",
        "georgian lari": "gel",
        "azerbaijani manat": "azn",
        "uzbekistani som": "uzs",
        "kazakhstani tenge": "kzt",
        "afghan afghani": "afn"
    };

    const fiatName = fiatCurrencies[fiat.toLowerCase()];
    return fiatName;
};